[package]
name = "bsnext_guards"
version = "0.22.1"
edition = "2021"

[dependencies]
urlpattern = { version = "0.3.0" }
serde = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
